### PR TITLE
CBMC: Strengthen various contracts

### LINKED ISSUE #291: CBMC: strengthen postcondition of polyvec_matrix_pointwise_montgomery()
In sign.c, we see the sequence
```   
 polyvec_matrix_pointwise_montgomery(&w1, mat, &z);
 polyveck_reduce(&w1);
```
At present, this will fail proof because the post-condition of the first call it not strong enough to satisfy the precondition of the call to `polyveck_reduce()`.

The postcondition of `polyvec_matrix_pointwise_montgomery()` must be strengthened accordingly.

### PR DESCRIPTION
**Pull request by rod-chapman**
Fixes #291 

1. Rename `REDUCE_RANGE_MAX` to `REDUCE32_RANGE_MAX` to help differentiate this constant from `MONTGOMERY_REDUCE_RANGE_MAX`.

2. Similarly, and for consistency, `REDUCE_DOMAIN_MAX` is renamed to `REDUCE32_DOMAIN_MAX`

3. Strengthen post-conditions and loop invariants of the following functions
```
montgomery_reduce()
polyvecl_pointwise_acc_montgomery()
polyvec_matrix_pointwise_montgomery()
```

4. Tests, proofs, lint all OK.

### CODE REVIEW

**Review by jakemas — APPROVED** [review]

**Comment by hanno-becker** [comment]
@rod-chapman See @mkannwischer comment above.

**Comment by hanno-becker** [comment]
Moving this to draft while it's blocked on CBMC.

**Review by jakemas — APPROVED** [review]

**Comment by jakemas** [comment]
looks good to me! My only comment is to squash down the commits to a single commit for a clean commit message, take out of draft mode!

File: mldsa/poly.h [hunk 1]
```diff
@@ -70,10 +70,12 @@ void poly_add(poly *r, const poly *b)
 __contract__(
   requires(memory_no_alias(b, sizeof(poly)))
   requires(memory_no_alias(r, sizeof(poly)))
-  requires(forall(k0, 0, MLDSA_N, (int64_t) r->coeffs[k0] + b->coeffs[k0] <= INT32_MAX))
+  requires(forall(k0, 0, MLDSA_N, (int64_t) r->coeffs[k0] + b->coeffs[k0] < REDUCE32_DOMAIN_MAX))
```
Comment (mkannwischer) [inline mldsa/poly.h:73]: Do we really need that pre-condition here (and the corresponding post-condition)?
The post-condition is already a functional spec of addition. So this reasoning should be possible on a higher level?

**Review by mkannwischer — APPROVED** [review]
Thanks @rod-chapman. Looks good to me. I have one non-blocking question, but we can resolve that in a follow-up.

File: mldsa/reduce.h [hunk 2]
```diff
@@ -10,18 +10,29 @@
...
+#define MONTGOMERY_REDUCE_STRONG_DOMAIN_MAX ((int64_t)INT32_MIN * -MLDSA_Q)
+
+
 #define montgomery_reduce MLD_NAMESPACE(montgomery_reduce)
 /*************************************************
  * Name:        montgomery_reduce
  *
  * Description: For finite field element a with
- *              -2^{31}MLDSA_Q <= a <= MLDSA_Q*2^31,
+ *              -2^{31}MLDSA_Q <= a < MLDSA_Q*2^31,
```
Comment (mkannwischer) [inline mldsa/reduce.h]: This deserves a better documentation of the two cases.
