### PR TITLE
Sign: Set smlen to 0 in case of failure

### LINKED ISSUE #974: Inconsistent and possibly confusing mld_sign() API and contracts
A pedantic reviewer points out:
```
File: mldsa/src/sign.c, in mld_sign:

c
ret = mld_sign_signature(sm, smlen, sm + MLDSA_CRYPTO_BYTES, mlen, ctx,
                         ctxlen, sk, context);
*smlen += mlen;
return ret;


If mld_sign_signature fails, it sets *siglen = 0. Then *smlen += mlen makes *smlen = mlen on failure. The CBMC contract says the function
should return *smlen == MLDSA_CRYPTO_BYTES + mlen on success, but doesn't constrain *smlen on failure. However, returning a non-zero
*smlen on failure could confuse callers into thinking there's valid data in the buffer. The mld_sign_open counterpart does set *mlen = 0
on failure.

Severity: Low (robustness). Consider setting *smlen = 0 on error for defensive consistency.
```

I tend to agree... we should set *smlen==0 on failure, and update the contracts and comments to match. Does this also affect the top-level API in mldsa_native.h?

### PR DESCRIPTION
**Pull request by mkannwischer**
- Resolves #974

### CODE REVIEW

File: mldsa/src/sign.c [hunk 1]
```diff
@@ -964,7 +966,10 @@ int mld_sign(uint8_t *sm, size_t *smlen, const uint8_t *m, size_t mlen,
   }
   ret = mld_sign_signature(sm, smlen, sm + MLDSA_CRYPTO_BYTES, mlen, ctx,
                            ctxlen, sk, context);
-  *smlen += mlen;
+  if (ret == 0)
```
Comment (rod-chapman) [inline mldsa/src/sign.c:1017]: Please update the comment(s) and the `ensures` contract for this function in sign.h
(or is it deliberately left under-specified?)

Comment (rod-chapman) [reply mldsa/src/sign.c:1017]: Do the comments at the top-level API in mldsa/mldsa_native.h also need to be updated?

Comment (mkannwischer) [reply mldsa/src/sign.c:1017]: I think the contract and comments exactly what we want to guarantee:
`(return_value == 0 && *smlen == MLDSA_CRYPTO_BYTES + mlen)`
WDYT @hanno-becker?


In the long term I think we should rather consider eliminating `smlen` altogether - see https://github.com/pq-code-package/mldsa-native/issues/789.

Comment (rod-chapman) [reply mldsa/src/sign.c:1017]: In the failure case(s), should we write *smlen==0 in the ensures clause, or leave it unspecified?

Comment (hanno-becker) [reply mldsa/src/sign.c:1017]: I'm in favor of harmonizing this with `mld_sign_signature`, and modify the post-condition from 
```c
  ensures((return_value == 0 && *smlen == MLDSA_CRYPTO_BYTES + mlen) ||
          (return_value == MLD_ERR_FAIL
           || return_value == MLD_ERR_OUT_OF_MEMORY
           || return_value == MLD_ERR_RNG_FAIL))
```
to
```c
  ensures((return_value == 0 && *smlen == MLDSA_CRYPTO_BYTES + mlen) ||
          ((return_value == MLD_ERR_FAIL || return_value == MLD_ERR_OUT_OF_MEMORY || return_value == MLD_ERR_RNG_FAIL) && *smlen == 0))
```

**Review by hanno-becker — CHANGES_REQUESTED** [review]
I agree with @rod-chapman that we should note in the CBMC contract for `mld_sign` that `*smlen == 0` if the function fails.

**Comment by mkannwischer** [comment]
> I agree with @rod-chapman that we should note in the CBMC contract for `mld_sign` that `*smlen == 0` if the function fails.

Okay. Adjusted.

**Review by hanno-becker — APPROVED** [review]
